# Generated by Django 4.1.7 on 2023-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="link",
            field=models.URLField(max_length=500),
        ),
    ]
